-- MySQL Script generated by MySQL Workbench
-- Sat Dec 11 14:28:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fullstack
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fullstack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fullstack` DEFAULT CHARACTER SET utf8 ;
USE `fullstack` ;

-- -----------------------------------------------------
-- Table `fullstack`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstack`.`tasks` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) NOT NULL,
  `finished` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fullstack`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstack`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstack`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstack`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `name` VARCHAR(64) NULL,
  `age` INT UNSIGNED NULL,
  `password` VARCHAR(45) NULL,
  `is_admin` TINYINT NULL,
  `address` VARCHAR(255) BINARY NULL,
  `picture` VARCHAR(255) CHARACTER SET 'koi8r' COLLATE 'koi8r_general_ci' BINARY NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `create_at` VARCHAR(45) NULL,
  `update_at` VARCHAR(45) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_cities1_idx` (`city_id` ASC),
  CONSTRAINT `fk_users_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `fullstack`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstack`.`users_ban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstack`.`users_ban` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reason` VARCHAR(255) NULL,
  `create_at` TIMESTAMP NULL,
  `time_ban` TIMESTAMP NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_ban_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_ban_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `fullstack`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstack`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstack`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `picture` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstack`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstack`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `vendor_code` VARCHAR(64) NULL,
  `name` VARCHAR(255) NULL,
  `price` FLOAT UNSIGNED NULL,
  `picture` VARCHAR(255) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `fullstack`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstack`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstack`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` FLOAT NOT NULL,
  `order_price` FLOAT NULL,
  `status` INT NULL,
  `created_at` TIMESTAMP NULL,
  `orderscol` VARCHAR(45) NULL,
  `product_id` INT NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_products1_idx` (`product_id` ASC),
  INDEX `fk_orders_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_orders_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `fullstack`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fullstack`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fullstack`.`basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fullstack`.`basket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` FLOAT NULL,
  `basketcol` VARCHAR(45) NULL,
  `product_id` INT NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_basket_products1_idx` (`product_id` ASC),
  INDEX `fk_basket_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_basket_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `fullstack`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_basket_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fullstack`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
